config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),  # avtomatik tarzda log in, log out, va boshqa built-in operatsiyalarni bajaradi, # avtomatik tarzda registration/login.html faylda ishlaydi 
]

if settings.DEBUG:
     urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import home, sign_up, create_post, PostUpdate, PostDetail, profile_view, ask_profile

urlpatterns = [
    path('', home, name='home'),
    path('home/', home, name='home'),
    path('sign-up/', sign_up, name='sign_up'),
    path('create-post/', create_post, name='create_post'),
    path('update-post/<int:pk>', PostUpdate.as_view(), name='update-post'),
    path('detail-post/<int:pk>', PostDetail.as_view(), name='detail-post'),
    path('profile/', profile_view, name='profile'),
    path('ask-profile/', ask_profile, name='ask-profile'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='software_image/', blank=True, null=True)

    def __str__(self):
        return f"{self.title} {self.description}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='user_picture/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm  # built-in class form to create a user registration. Creates user
from django.contrib.auth.models import User
from .models import Post, Profile


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)     # by default UserCreationForm has no email field so we add manually

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['image', 'title', 'description']


class ProfileUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Profile
        fields = ['user', 'bio', 'email', 'profile_picture']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user:
            self.fields['email'].initial = user.email

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.user.email = self.cleaned_data['email']
        profile.user.save()
        if commit:
            profile.save()
        return profile

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from .forms import RegisterForm, PostForm, ProfileUpdateForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from .models import Post, Profile
from django.views import View
from django.contrib.auth.models import User

# Create your views here.


@login_required(login_url='/login')
def home(request):
    query = request.GET.get('query') # tuple -- ('query','')
    posts = Post.objects.all()


    if query:
        posts = posts.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(author__username__icontains=query)
        )

    paginator = Paginator(posts, 2)
    page_number = request.GET.get("page")

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        post_id = request.POST.get('post-id')
        post = Post.objects.filter(id=post_id).first()
        if post and post.author == request.user:
            post.delete()
            return render(request, 'main/home.html', {'page_obj': page_obj, 'query': query})
    # print(posts.image.url)


    return render(request, 'main/home.html', {'page_obj': page_obj, 'query': query})



# def home(request):
#
#
#     posts = Post.objects.all()
#
#     return render(request, 'main/home.html', {'posts': posts})


@login_required(login_url='/login')
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/home')

    else: form = PostForm()
    return render(request, 'main/create_post.html', {'form': form})

def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)  # request.POST posting data to form
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('ask-profile')
    else:                                   # agar user
        form = RegisterForm()   # if there is no data, and request method is not POST, instead it is GET we just create a form

    return render(request, 'registration/sign_up.html', {'form': form})


# CRUD

class PostUpdate(View):
    template_name = 'main/update.html'

    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(instance=post)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST, request.FILES, instance=post)  # Fix applied

        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('detail-post', kwargs={'pk': post.pk}))

        return render(request, self.template_name, {'form': form})


class PostDetail(View):

    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'main/detail.html', {'post': post})


# @login_required
# def profile_view(request):
#
#     profile = Profile.objects.get_or_create(user=request.user)
#     return render(request, 'main/profile.html', {'profile': profile})


@login_required
def profile_view(request):
    # profile, created = Profile.objects.get_or_create(user=request.user)
    profile = request.user.profile

    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')

    else:
        form = ProfileUpdateForm(instance=profile, user=request.user)

    return render(request, 'main/profile.html', {'form': form, 'profile': profile})


def ask_profile(request):
    return render(request, 'main/ask_profile.html')





# @login_required(login_url='/login')     # login_url=...  agar biz login qilmagan bo'lsak bizni ... url da yuboradi. Ishlashi: agar login qilinmagan bo'lsa home page ga qo'ymaydi 'login/' pageda turaveradi
# def home(request):
#     query = request.GET.get('query')
#     posts = Post.objects.all()
#
#     if query:
#         posts = posts.filter(Q(name__icontains=query) | Q(description__icontains=query))
#
#
#     paginator = Paginator(posts, 2)
#     page_number = request.GET.get("page")
#     page_obj = paginator.get_page(page_number)
#
#
#     if request.method == 'POST':
#         post_id = request.POST.get('post-id')
#         post = Post.objects.filter(id=post_id).first()
#         if post and post.author == request.user:
#             post.delete()
#
#         posts = Post.objects.all()
#         paginator = Paginator(posts, 2)
#         page_obj = paginator.get_page(page_number)
#
#     return render(request, 'main/home.html', {'page_obj': page_obj, 'query': query, 'posts': posts})



# class SoftwareList(LoginRequiredMixin, View):
#     login_url = 'login'
#     def get(self, request):
#
#         query = request.GET.get('query')
#         posts = Post.objects.all()
#         user = request.user
#         if query:
#             posts = Post.objects.filter(Q(name__icontains=query) | Q(price__icontains=query))
#
#
#         paginator = Paginator(posts, 2)
#         page_number = request.GET.get("page")
#         page_obj = paginator.get_page(page_number)
#         return render(request, 'main/home.html', {'page_obj': page_obj, 'user': user})
#
#     def post(self, request):
#         posts = Post.objects.all()
#         if request.method == 'POST':
#             post_id = request.POST.get('post-id')
#             post = Post.objects.filter(id=post_id).first()
#             if post and post.author == request.user:
#                 post.delete()
#
#         paginator = Paginator(posts, 2)
#         page_number = request.GET.get("page")
#         page_obj = paginator.get_page(page_number)
#         return render(request, 'main/home.html', {'page_obj': page_obj})

main/templates/main/ask_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chose option</title>
</head>
<body>
<a href="{% url 'profile' %}">Yes</a><br>
<a href="{% url 'home' %}">No</a>
</body>
</html>

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}My Site{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div>
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/home">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/create-post">Add Software</a>
            </li>
          </ul>
        </div>
        <div>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <span class="navbar-text">Logged in as {{user.username}} | </span>
            <li class="nav-item">
              <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link" style="border: none; background: none; padding: 0;">
                  Logout
                </button>
              </form>
              {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
    </li>
              {% endif %}

            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

main/templates/main/create_post.html
{% extends 'main/base.html' %} {% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} {% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}{{form.as_p}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

main/templates/main/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<div class="container">
    {% if post.image %}
    <img src="{{ post.image.url }}" class="post-img"
         onerror="this.onerror=null; this.src='https://via.placeholder.com/800x400?text=No+Image';">
    {% else %}
        <img src="default.jpeg" class="post-img">
    {% endif %}
</div>

    <h1 class="post-title">{{ post.title}}</h1>


    <div class="description">
        <h3>Technical info:</h3>
        <p>{{ post.description }}</p>
    </div>
    <a href="{% url 'home' %}" class="back-btn">⬅️ Back to List</a><br>
    <a href="{% url 'update-post' post.id %}" class="back-btn">⬅️ Update</a><br>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home Page{% endblock %}
{% block content %}

<!-- Search Form -->
<form method="GET" action="{% url 'home' %}" class="mb-3">
  <input type="text" name="query" value="{{ query }}" placeholder="Search posts..." class="form-control d-inline-block w-50" />
  <button type="submit" class="btn btn-primary">Search</button>
</form>

{% for post in page_obj %}
<div class="card mt-2">
  <div class="card-header"><strong>@{{ post.author.username }}</strong></div>
  <div class="card-body d-flex flex-row justify-content-between">
    <div>
      <h3 class="card-title">{{ post.title }}</h3>
      <p>{{ post.description }}</p>
      <a href="/detail-post/{{ post.pk }}" class="post-image">
        {% if post.image %}
        <img src="{{ post.image.url }}" alt="Post Image" class="img-fluid rounded mt-2" style="max-width: 300px;">
          {% else %}
                  <img src="https://t4.ftcdn.net/jpg/00/65/77/27/240_F_65772719_A1UV5kLi5nCEWI0BNLLiFaBPEkUbv5Fv.jpg" alt="Post Image" class="img-fluid rounded mt-2" style="max-width: 300px;">

        {% endif %}
      </a>
    </div>
    <div>
      {% if user == post.author or perms.main.delete_post %}
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" name="post-id" value="{{ post.id }}">
          Delete
        </button>
      </form>
      {% endif %}
      {% if user.is_staff %}
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-warning" name="user-id" value="{{ post.author.id }}">
          Ban User
        </button>
      </form>
      {% endif %}
    </div>
  </div>
  <div class="card-footer text-muted">{{ post.created_at }}</div>
</div>
{% empty %}
<p>No posts found.</p>
{% endfor %}

<!-- Pagination Controls -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

main/templates/main/profile.html
{% extends 'main/base.html' %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{{ profile.user.username }}'s Profile</h2>

    {% if profile.profile_picture %}
        <img src="{{ profile.profile_picture.url }}" alt="Profile Picture" class="img-fluid rounded-circle" style="max-width: 150px;">
    {% else %}
        <p>No profile picture uploaded</p>
    {% endif %}

    <p><strong>Email:</strong> {{ profile.user.email }}</p>
    <p><strong>Bio:</strong> {{ profile.bio }}</p>

    <h3>Edit Profile</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}


        {{ form.as_p }}

        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

main/templates/main/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>
</body>
</html>